import esbuild from "esbuild";
import { builtinModules } from "node:module";
import { copyFileSync, mkdirSync, watchFile, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// NOTE: this file is a *build script*. It is never bundled into main.js, so the
// "no Node APIs" rule in the spec does not apply here. src/ is type-checked with
// `"types": []`, which makes importing fs/path from plugin code a compile error.

const root = dirname(fileURLToPath(import.meta.url));
const isProd = process.argv[2] === "production";

// Dev builds go straight into the throwaway test vault so the Hot Reload plugin
// can pick them up. Production builds land next to manifest.json for release.
const outDir = isProd
  ? root
  : join(root, "test-vault", ".obsidian", "plugins", "doms");

const STATIC_FILES = ["manifest.json", "styles.css"];

function syncStatic() {
  if (outDir === root) return;
  mkdirSync(outDir, { recursive: true });
  for (const file of STATIC_FILES) {
    copyFileSync(join(root, file), join(outDir, file));
  }
  // Marker file for pjeby/obsidian-hot-reload.
  writeFileSync(join(outDir, ".hotreload"), "");
}

const banner = `/* D.O.M.S — generated by esbuild. Edit src/, not this file. */`;

/** Keeps styles.css and manifest.json in lockstep with every main.js write. */
const syncStaticPlugin = {
  name: "doms-sync-static",
  setup(build) {
    build.onEnd(() => syncStatic());
  },
};

/** @type {import("esbuild").BuildOptions} */
const options = {
  banner: { js: banner },
  entryPoints: [join(root, "src/main.ts")],
  bundle: true,
  outfile: join(outDir, "main.js"),
  format: "cjs",
  target: "es2018",
  platform: "browser",
  logLevel: "info",
  plugins: isProd ? [] : [syncStaticPlugin],
  sourcemap: isProd ? false : "inline",
  treeShaking: true,
  minify: isProd,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
};

mkdirSync(outDir, { recursive: true });
syncStatic();

if (isProd) {
  await esbuild.build(options);
  process.exit(0);
}

const ctx = await esbuild.context(options);
await ctx.watch();

// esbuild only watches the JS import graph, so styles.css and manifest.json
// need their own watcher.
//
// watchFile (stat polling), not watch (inotify): inotify follows the inode, so
// any editor that saves by writing a temp file and renaming it over the target
// silently detaches the watcher and CSS edits stop reaching the vault.
for (const file of STATIC_FILES) {
  watchFile(join(root, file), { interval: 300 }, (curr, prev) => {
    if (curr.mtimeMs === prev.mtimeMs && curr.size === prev.size) return;
    syncStatic();
    console.log(`[doms] synced ${file}`);
  });
}

console.log(`[doms] watching. output -> ${outDir}`);
